### ISSUE TITLE
Configure startup

### ISSUE THREAD

**Issue by msbense** [team5181/pi#2]

**Comment by thefangbear** [comment]
Currently I didn't add startup scripts to rc.d because they still have compatibility issues, which hopefully will be solved tomorrow. I'm not sure which problem you are adddressing but that's what I've been working on.

**Comment by msbense** [comment]
Done as of some time this week (3/29 to 5/4)

**Comment by thefangbear** [comment]
I actually didn't. It's somewhere on Github but not yet deployed to the robot.
